name: "gprofiler2_gost"
description: runs a functional enrichment analysis with gprofiler2
keywords:
  - gene set analysis
  - enrichment
  - gprofiler2
  - gost
  - gene set
tools:
  - "gprofiler2":
      description: "An R interface corresponding to the 2019 update of g:Profiler web tool."
      homepage: "https://gl.cs.ut.ee/biit/r-gprofiler2"
      documentation: "https://rdrr.io/cran/gprofiler2/"
      tool_dev_url: "https://gl.cs.ut.ee/biit/r-gprofiler2"
      doi: "10.1093/nar/gkad347"
      licence: "['GPL v2']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing contrast information, e.g. [ variable:'treatment', reference:'treated', control:'saline', blocking:'' ]
  - de_file:
      type: file
      pattern: "*.{csv,tsv}"
      description: |
        CSV or TSV-format tabular file with differential analysis outputs
  - de_id_column:
      type: string
      description: |
        The column in the differential expression file that should be used as ID for the DE genes
  - organism:
      type: string
      description: |
        The name of the analyzed organism consisting of the first letter of the genus and the entire species name, e.g. for homo sapiens: hsapiens
  - significant:
      type: boolean
      description: |
        Whether the pathway enrichment results should be restricted to significant ones (if true, default) or all results should be considered (if false)
  - measure_underrepresentation:
      type: boolean
      description: |
        Whether the genes should be tested for underrepresentation in pathways isntead of for overrepresentation (default false)
  - correction_method:
      type: string
      description: |
        Which method to use for multiple testing correction, one of "gSCS" (default, synonyms: "analytical", "g_SCS"), "fdr" (synonym: "false_discovery_rate"), "bonferroni"
      pattern: "gSCS|analytical|g_SCS|fdr|false_discovery_rate|bonferroni"
  - sources:
      type: string
      description: |
        Comma-separated list of data sources to search for pathways, e.g. 'GO,REAC'. Check https://rdrr.io/cran/gprofiler2/man/gost.html for a list of available sources
  - evcodes:
      type: boolean
      description: |
        Whether to include evidence codes in the results, may decrease performance (default false). Check https://rdrr.io/cran/gprofiler2/man/gost.html for more info
  - pval_threshold:
      type: string
      description: |
        p value threshold for determining which results are significant (default 0.05)
  - gmt_file:
      type: file
      pattern: "*.{gmt}"
      description: |
        Path to a GMT file that should be used as a custom datasource instead of online databases
  - gost_id:
      type: string
      description: |
        ID of a previous gprofiler query with a GMT file that should be used as a custom datasource instead of online databases
  - background_file:
      type: file
      pattern: "*.{txt}"
      description: |
        Path to a TXT file listing gene IDs (one per line) that should be used as the background (will override count_file)
  - count_file:
      type: file
      pattern: "*.{csv,tsv}"
      description: |
        Path to a CSV/TSV file containing expression values of genes that should be used as the background; will only use genes with an expression rowsum > 0
  - domain_scope:
      type: string
      description: |
        How to define statistical domain, one of "annotated" (default), "known", "custom" or "custom_annotated". Check https://rdrr.io/cran/gprofiler2/man/gost.html for more info
      pattern: "annotated|known|custom|custom_annotated"
  - min_diff:
      type: integer
      description: How many enriched differential genes a pathway should contain to be considered in the results (default 1)
  - round_digits:
      type: integer
      description: |
        Number of digits to which to round the values in the output tables. Default -1, will not round
  - enrich_colors:
      type: string
      description: |
        Comma-separated list of two colors for the enrichment plots, first value is for high enrichment, second is for low. Can be any color ggplot2 accepts, e.g. "#132B43,white". Default: "#132B43,#56B1F7"

output:
  - all_enrich:
      type: file
      description: |
        TSV file; table listing all enriched pathways that were found
  - rds:
      type: file
      description: |
        RDS file; R object containing the results of the gost query
  - plot_png:
      type: file
      description: |
        PNG file; Manhattan plot of all enriched pathways
  - plot_html:
      type: file
      description: |
        HTML file; interactive Manhattan plot of all enriched pathways
  - sub_enrich:
      type: file
      description: |
        TSV file; table listing enriched pathways that were found from one particular source
  - sub_plot:
      type: file
      description: |
        PNG file; bar plot showing the fraction of genes that were found enriched in each pathway
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@WackerO"
